burger=document.querySelector('.burger');
navbar=document.querySelector('.navbar');
right=document.querySelector('.right-nav');
navlist=document.querySelector('.nav-list');
burger.addEventListener('click',()=>{
navbar.classList.toggle('h-nav');
right.classList.toggle('v-class');
navlist.classList.toggle('v-class');
})